spring:
  application:
    name: auction-eureka

server:
  port: 8761 #???? ??

eureka:
  client:
    register-with-eureka: false # default : true
    fetch-registry: false # default : true

# Eureka Libray? ????? ??? ????? Eureka Client?? ???? ???? ??? ???????.
# ??? true? ???? ?? ??? ??? ???? ???? ???? ??? ?? ????? false? ?? ?????.